version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  pipeline:
    steps:
      - checkout
      - go/install:
          cache: true
          version: 1.20.3
      - run:
          name: Install Mage
          command: go install github.com/magefile/mage@300bbc868ba8f2c15b35e09df7e8804753cac00d
      - run:
          command: mage all

workflows:
  pipeline:
    jobs:
      - pipeline

