version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  pipeline:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Mage
          command: go install github.com/magefile/mage@300bbc868ba8f2c15b35e09df7e8804753cac00d
      - run:
          command: mage all

workflows:
  pipeline:
    jobs:
      - pipeline
